---
# see https://github.com/FGasper/perl-github-action-tips

name: Test Code on BSD
permissions:
  contents: read
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            version: '13.3'
            pkginstall: pkg install -y p5-ExtUtils-MakeMaker p5-Test-Most p5-Test-Warn p5-String-Util p5-Test-Compile p5-Test-Needs p5-Test-NoWarnings p5-Test-Requires
          - name: openbsd
            version: '7.5'
            pkginstall: pkg_add p5-ExtUtils-MakeMaker

    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo hostname example.com
            sudo ${{ matrix.os.pkginstall }}
            sudo cpan -iT Lingua::Conjunction String::Clean Test::Carp
            curl -L https://cpanmin.us | sudo perl - --notest --installdeps --with-configure --with-develop .
            sudo chown -R runner:runner .
            AUTOMATED_TESTING=1 perl Makefile.PL
            AUTOMATED_TESTING=1 make
            AUTOMATED_TESTING=1 prove -wlmb t
